tags:
  shb-ui: true
  shb-back: true
  shb-postgres: true
  shb-rabbit: true


global:
  imagepullsecrets: regcred

  ingress:
    host: test.host
    ui_port: 80
    back_port: 8080

  # если необходимо использовать базу вне kubernetes
  # Разблокировать и установить флаг для блокировки чата tags.shb-postgres=false
  # postgres_host: 192.168.4.220

  postgres:
    port: "5432"
    schema: shb_develop
    user: test_user
    password: qwerty

  # если необходимо использовать rabbitmq вне kubernetes
  # Разблокировать и установить флаг для блокировки чата tags.shb-rabbit=false
  # rabbit_host: 192.168.4.220
  rabbitmq:
    port: "5672"
    username: serg
    password: qwerty
    virtualHost: my_vhost
