tags:
  shb-ui: true


global:
  imagepullsecrets: regcred

  ingress:
    host: test.host
    ui_port: 80
    back_port: 8080

  postgres:
    port: "5432"
    schema_shb: test_database
    schema_adapter: shb_adapter_database
    user: test_user
    password: qwerty

  rabbitmq:
    host: shb-rabbit
    port: "5672"
    username: serg
    password: qwerty
    virtualHost: my_vhost
