apiVersion: v1
kind: Pod
metadata:
  name: my-postgres
  labels:
    app: my-postgres
spec:
  containers:
  - name: my-postgres
    image: dc2.my-bg.ru/shb/postgres:10
    imagePullPolicy: IfNotPresent
    env:
      - name: POSTGRES_DB
        value: test_database
      - name: POSTGRES_PASSWORD
        value: qwerty
      - name: POSTGRES_USER
        value: test_user
    ports:
      - containerPort: 5432
  imagePullSecrets:
    - name: regcred

