# Default values for shb-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dc2.my-bg.ru/shb/shb-ui
  tag: 
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
