apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "shb-ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "shb-ui.name" . }}
    helm.sh/chart: {{ include "shb-ui.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "shb-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "shb-ui.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - env:
            - name: API_SERVER
              value: http://{{.Values.global.host}}/api
            - name: DISABLE_ENDPOINT_ERROR_HANDLING
              value: "true"
            - name: HOST
              value: {{ .Values.global.host}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - containerPort: 443
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.global.imagepullsecrets}}




