apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "shb-postgres.fullname" . }}
  labels:
    app: {{ template "shb-postgres.name" . }}
    chart: {{ template "shb-postgres.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: {{ include "shb-postgres.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "shb-postgres.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "shb-postgres.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagepullsecrets }}
      containers:
        - name: {{ template "shb-postgres.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.global.back.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.back.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.global.back.postgres.schema | quote }}
          ports:
            - containerPort: 5432
