apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cool-postgres
spec:
  serviceName: "cool-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: cool-postgres
  template:
    metadata:
      labels:
        app: cool-postgres
    spec:
      containers:
        - name: postgres
          image: dc2.my-bg.ru/shb/postgres:10
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: test_database
            - name: POSTGRES_PASSWORD
              value: qwerty
            - name: POSTGRES_USER
              value: test_user
          ports:
            - containerPort: 5432
      imagePullSecrets:
        - name: regcred