apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-shb-back
"data": {
  "application.properties": "{{ range .Files.Lines "files/application.properties" }}{{ (printf "%s\n" . ) }}{{ end }}"
}