apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shb-back.fullname" . }}
  labels:
    app.kubernetes.io/name: "shb-back"
    helm.sh/chart: {{ include "shb-back.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "shb-back"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "shb-back"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: "wait-for-db"
        image: "{{ .Values.initContainerImage }}"
        command:
          - 'sh'
          - '-c'
          - >
            until nc -z -w 2 {{ .Release.Name }}-shb-postgres 5432 && echo database ok; do
              sleep 2;
            done;
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: {{ .Values.configPath }}/
            - name: cookies-domain
              value: {{ .Values.global.ingress.host}}
            - name: postgres.host
              value: {{.Values.global.postgres_host | default ( printf "%s-%s" .Release.Name "shb-postgres")  }}
            - name: keystore.path
              value: {{ .Values.configPath }}/keystores/shb.jks
            {{- range $key, $value := .Values.global.postgres }}
            - name: postgres.{{$key}}
              value: {{ $value | quote}}
            {{- end }}
            - name: rabbitmq.host
              value: {{.Values.global.rabbit_host | default ( printf "%s-%s" .Release.Name "shb-rabbit")  }}
            {{- range $key, $value := .Values.global.rabbitmq }}
            - name: rabbitmq.{{$key}}
              value: {{ $value | quote}}
            {{- end }}
          {{- if .Values.back.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: '/info'
              port: 8080
            initialDelaySeconds: {{ .Values.back.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.back.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.back.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.back.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.back.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.back.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: '/info'
              port: 8080
            initialDelaySeconds: {{ .Values.back.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.back.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.back.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.back.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.back.livenessProbe.successThreshold }}
           {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.configPath }}
            - name: jks-volume
              mountPath: {{ .Values.configPath }}/keystores
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-shb-back
        - name: jks-volume
          configMap:
            name: {{ .Release.Name }}-shb-jks
      imagePullSecrets:
        - name: {{ .Values.global.imagepullsecrets}}
      restartPolicy: Always