# Default values for shb-back.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

initContainerImage: "alpine:3.6"

image:
  repository: dc2.my-bg.ru/shb/shb
  tag: 1.1.0.197
  pullPolicy: IfNotPresent

configPath: /conf

service:
  type: ClusterIP
  port: 8080

migration:
  image: dc2.my-bg.ru/shb/shb_patches

postgres:
  enabled: true
  port: "5432"
  schema: db
  user: user
  password: qwerty
db:
  host:

back:
  livenessProbe:
    enabled: false
    initialDelaySeconds: 180
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1

  readinessProbe:
    enabled: false
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1