# Default values for shb-back.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dc2.my-bg.ru/shb/shb
  tag: SNAPSHOT-1.0.0.118
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
configPath: /conf

service:
  type: ClusterIP
  port: 8080